# Generated by Django 5.1 on 2024-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testTM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='choix_long_term',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='cinq_marque_frs_femme',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='cinq_marque_frs_homme',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='redaction_email_colab',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='remunere',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='salaire',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='strategie_convincre',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='traite',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='travailler_soir',
            field=models.CharField(max_length=255),
        ),
    ]
