# Generated by Django 5.1.4 on 2025-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretiendev',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entretiendev',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='entretiendev',
            name='technical_skills_frameworks',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='entretiendev',
            name='technical_skills_languages',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='entretiendev',
            name='technical_skills_selected_language_level',
            field=models.TextField(default='""'),
        ),
    ]
