# Generated by Django 5.1.4 on 2025-01-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDev', '0003_rename_technical_skills_frameworks_entretiendev_frameworks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretiendev',
            name='frameworks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='entretiendev',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='entretiendev',
            name='selectedLanguageLevel',
            field=models.CharField(default='', max_length=255),
        ),
    ]
